### PR TITLE
Some simplifications to LV2 wrapper

### PR DESCRIPTION
**Pull request by mzuther**
Hi falkTX,

in order to make updating the LV2 wrapper to the multichannel API easier, I have simplified the wrapper a little bit.  I didn't get very far, but while I was doing this, I have also suppressed two warnings about unused variables.  Can't hurt... :)

Best,

Martin

### CODE REVIEW

**Comment by falkTX** [comment]
Please don't use custom unused macros, juce already has one defined.
Use the one from juce instead. afaik it's called 'ignoreUnused()'

**Comment by falkTX** [comment]
The 2nd commit `simplified LV2 wrapper (less obsolete constants)` looks fine.
Fix up the macro usage on the 1st one and I'll merge it. Thanks.

**Comment by falkTX** [comment]
Alright, thanks again!

**Comment by mzuther** [comment]
Thanks for pointing me to the JUCE macro. I hadn't noticed it... :)

**Pull request merged**
