### PR TITLE
Distrho update 5.3.0

### PR DESCRIPTION
**Pull request by jpcima**
Hi, this is an update to the next release of JUCE.
I kept a journal of conflict resolutions which I listed below.

From experience, it's the ideal strategy to proceed version by version, as trying the entire thing at once is a guaranteed path to insanity.

The idea is to push incremental updates into a branch distrho-update such that master is preserved for the time being.

Past the version 5.3.2, VST support will disappear.
However, I prefer to keep adding Vestige update for the end, because there exist a ton of breaking upstream VST updates leading to the final release.
In particular, all identifiers of "VST interface" things were substituted in the transition from Juce's to Steinberg's, requiring to do all the work over.

# Update 5.2.1 to 5.3.0

- juce_JUCESplashScreen.{h,cpp}
  Delete these telemetry-related source files (ours)

- examples/**/AppConfig.h
  Delete these example files, considering all were grouped into a single DemoRunner (theirs)

- juce_audio_basics.{h,cpp}
  Remove the old check which would force disabling SIMD intrinsics on MinGW compilers. (theirs)

- juce_AudioDeviceManager.h
  Removed old inner class `LevelMeter`, which has its declaration moved elsewhere in the file. (theirs)

- juce_AudioDeviceManager.cpp
  `createAudioDeviceTypes`: keep ALSA in the list (ours), add Oboe (theirs)
  Misc updates regarding the change of `LevelMeter` class. (theirs)

- juce_VST3Headers.h
  Remove fthread.cpp inclusion (theirs)
  Add some conditional inclusions based on SDK version (theirs)
  Removed the redefinition `_set_abort_behavior(...)` on MinGW (theirs)

- juce_audio_processors.cpp
  Update the include list (theirs), keep juce_AudioProcessorEditor enclosed in `! JUCE_AUDIOPROCESSOR_NO_GUI` (ours)

- juce_AudioProcessor.h
  Update a block of instance variable declarations (theirs), caring to not break a `! JUCE_AUDIOPROCESSOR_NO_GUI` conditional (ours)

- juce_AudioProcessor.cpp
  Update a destructor comment (theirs), conserving the `! JUCE_AUDIOPROCESSOR_NO_GUI` check around it (ours)

- juce_XmlElement.cpp
  Reindent a switch body (theirs), insert a GCC-style "fall-through" comment (ours)

- juce_ResizableWindow.cpp
  Eliminate the instantiation of telemetry-related splash screen (ours)

- juce_ProjectSaver.h
  Eliminate the generation of telemetry-related AppConfig.h parts (ours)

- Build Projucer and resave all projects
  `find . -name '*.jucer' -exec ./extras/Projucer/Builds/LinuxMakefile/build/Projucer --resave {} \;`

# Other

- Removed `JUCE_SNAP_TO_ZERO` from `IIRFilterOld`, which has become a redundancy with global definitions.

### CODE REVIEW

**Comment by falkTX** [comment]
I appreciate the update, very nice!
Obviously, I cant review this, but it is juce stuff anyway so... not going to bother too much.
Feel free to merge anytime. (I gave you RW access to this repo, right?)

**Comment by jpcima** [comment]
Sure it's no problem for me to merge this. I created the special branches for the purpose.
Is this repository activated on Travis-CI, such that I can build the demo set ?

**Comment by falkTX** [comment]
there is no travis/CI for this repo, feel free to add it.

**Comment by jpcima** [comment]
@falkTX, I find a previous one of your commits. Do you recall what's the purpose of this commit, and is it safe to revert it? 9027e7a

Not only it conflicts, also it breaks the Xcode build altogether. (has override on method definitions)

**Comment by falkTX** [comment]
That was used for carla, but I no longer need it since I made my own osx window class now.
So you can revert yes

**Comment by jpcima** [comment]
>there is no travis/CI for this repo, feel free to add it.

Done but it needs enabling at travis-side: https://travis-ci.org/distrho/juce

**Comment by falkTX** [comment]
Done

**Pull request merged**
